data_in =[('LanguageWorkedWith', 'Assembly'),
 ('LanguageWorkedWith', 'Bash/Shell/PowerShell'),
 ('LanguageWorkedWith', 'C'),
 ('LanguageWorkedWith', 'C#'),
 ('LanguageWorkedWith', 'C++'),
 ('LanguageWorkedWith', 'Dart'),
 ('LanguageWorkedWith', 'Go'),
 ('LanguageWorkedWith', 'HTML/CSS'),
 ('LanguageWorkedWith', 'Haskell'),
 ('LanguageWorkedWith', 'Java'),
 ('LanguageWorkedWith', 'JavaScript'),
 ('LanguageWorkedWith', 'Julia'),
 ('LanguageWorkedWith', 'Kotlin'),
 ('LanguageWorkedWith', 'Objective-C'),
 ('LanguageWorkedWith', 'PHP'),
 ('LanguageWorkedWith', 'Perl'),
 ('LanguageWorkedWith', 'Python'),
 ('LanguageWorkedWith', 'R'),
 ('LanguageWorkedWith', 'Ruby'),
 ('LanguageWorkedWith', 'Rust'),
 ('LanguageWorkedWith', 'SQL'),
 ('LanguageWorkedWith', 'Scala'),
 ('LanguageWorkedWith', 'Swift'),
 ('LanguageWorkedWith', 'TypeScript'),
 ('LanguageWorkedWith', 'VBA'),
 ('DatabaseWorkedWith', 'Cassandra'),
 ('DatabaseWorkedWith', 'Couchbase'),
 ('DatabaseWorkedWith', 'DynamoDB'),
 ('DatabaseWorkedWith', 'Elasticsearch'),
 ('DatabaseWorkedWith', 'Firebase'),
 ('DatabaseWorkedWith', 'IBM DB2'),
 ('DatabaseWorkedWith', 'MariaDB'),
 ('DatabaseWorkedWith', 'Microsoft SQL Server'),
 ('DatabaseWorkedWith', 'MongoDB'),
 ('DatabaseWorkedWith', 'MySQL'),
 ('DatabaseWorkedWith', 'Oracle'),
 ('DatabaseWorkedWith', 'PostgreSQL'),
 ('DatabaseWorkedWith', 'Redis'),
 ('DatabaseWorkedWith', 'SQLite'),
 ('WebframeWorkedWith', 'ASP.NET'),
 ('WebframeWorkedWith', 'ASP.NET Core'),
 ('WebframeWorkedWith', 'Angular'),
 ('WebframeWorkedWith', 'Angular.js'),
 ('WebframeWorkedWith', 'Django'),
 ('WebframeWorkedWith', 'Drupal'),
 ('WebframeWorkedWith', 'Express'),
 ('WebframeWorkedWith', 'Flask'),
 ('WebframeWorkedWith', 'Gatsby'),
 ('WebframeWorkedWith', 'Laravel'),
 ('WebframeWorkedWith', 'React.js'),
 ('WebframeWorkedWith', 'Ruby on Rails'),
 ('WebframeWorkedWith', 'Spring'),
 ('WebframeWorkedWith', 'Symfony'),
 ('WebframeWorkedWith', 'Vue.js'),
 ('WebframeWorkedWith', 'jQuery'),
 ('MiscTechWorkedWith', '.NET'),
 ('MiscTechWorkedWith', '.NET Core'),
 ('MiscTechWorkedWith', 'Ansible'),
 ('MiscTechWorkedWith', 'Apache Spark'),
 ('MiscTechWorkedWith', 'Chef'),
 ('MiscTechWorkedWith', 'Cordova'),
 ('MiscTechWorkedWith', 'Flutter'),
 ('MiscTechWorkedWith', 'Hadoop'),
 ('MiscTechWorkedWith', 'Keras'),
 ('MiscTechWorkedWith', 'Node.js'),
 ('MiscTechWorkedWith', 'Pandas'),
 ('MiscTechWorkedWith', 'Puppet'),
 ('MiscTechWorkedWith', 'React Native'),
 ('MiscTechWorkedWith', 'TensorFlow'),
 ('MiscTechWorkedWith', 'Teraform'),
 ('MiscTechWorkedWith', 'Torch/PyTorch'),
 ('MiscTechWorkedWith', 'Unity 3D'),
 ('MiscTechWorkedWith', 'Unreal Engine'),
 ('MiscTechWorkedWith', 'Xamarin'),
 ('skills_clusters', 'skills_group_0'),
 ('skills_clusters', 'skills_group_1'),
 ('skills_clusters', 'skills_group_10'),
 ('skills_clusters', 'skills_group_11'),
 ('skills_clusters', 'skills_group_12'),
 ('skills_clusters', 'skills_group_13'),
 ('skills_clusters', 'skills_group_14'),
 ('skills_clusters', 'skills_group_15'),
 ('skills_clusters', 'skills_group_16'),
 ('skills_clusters', 'skills_group_2'),
 ('skills_clusters', 'skills_group_3'),
 ('skills_clusters', 'skills_group_4'),
 ('skills_clusters', 'skills_group_5'),
 ('skills_clusters', 'skills_group_6'),
 ('skills_clusters', 'skills_group_7'),
 ('skills_clusters', 'skills_group_8'),
 ('skills_clusters', 'skills_group_9')]
 